### ISSUE TITLE
Update ValueAtRisk.jl 

### ISSUE THREAD

**Issue by shayandavoodii** [chm-von-tla/ValueAtRisk.jl#12]
Hi,
Since installing your package require a lot of downgrades for many other packages, please consider updating your package:
```julia
  [a93c6f00] ↓ DataFrames v1.3.4 ⇒ v0.22.7
  [31c24e10] ↓ Distributions v0.25.65 ⇒ v0.24.18
    Updating `C:\Users\Shayan\.julia\environments\v1.7\Manifest.toml`
  [49dc2e85] - Calculus v0.5.1
  [324d7699] ↓ CategoricalArrays v0.10.6 ⇒ v0.9.7
  [a93c6f00] ↓ DataFrames v1.3.4 ⇒ v0.22.7
  [b429d917] - DensityInterface v0.4.0
  [31c24e10] ↓ Distributions v0.25.65 ⇒ v0.24.18
  [fa6b7ba4] - DualNumbers v0.6.8
  [1a297f60] ↓ FillArrays v0.13.2 ⇒ v0.11.9
  [34004b35] - HypergeometricFunctions v0.3.11
  [e1d29d7a] ↓ Missings v1.0.2 ⇒ v0.4.5
  [08abe8d2] ↓ PrettyTables v1.3.1 ⇒ v0.11.1
  [f2b01f46] ↓ Roots v2.0.2 ⇒ v1.2.0
  [a2af1166] ↓ SortingAlgorithms v1.0.1 ⇒ v0.3.1
  [276daf66] ↓ SpecialFunctions v2.1.7 ⇒ v1.8.7
  [4c63d2b9] ↓ StatsFuns v1.0.1 ⇒ v0.9.18
```

**Comment by chm-von-tla** [comment]
Thanks for the interest in this package. I'll look into it in the following days

**Comment by shayandavoodii** [comment]
Glad to find this library. But I got disappointed because of the downgrades. I hope you'll consider updating the dependencies and stuff.

**Comment by chm-von-tla** [comment]
> But I got disappointed because of the downgrades

You are right about that. The versions of the dependencies are ancient as of now

>  I hope you'll consider updating the dependencies and stuff.

I'm working on it right now. I am still getting the hang of using the auto-registering tools, but I'll have resolved the issues very soon.

**Comment by chm-von-tla** [comment]
The new version has been merged into the Julia Registry
```
@v1.7) pkg> up
    Updating registry at `~/.julia/registries/General.toml`
   Installed ValueAtRisk ─ v1.1.0
    Updating `~/.julia/environments/v1.7/Project.toml`
  [a6faba0b] ↑ ValueAtRisk v1.0.0 ⇒ v1.1.0
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [a4c015fc] + ANSIColoredPrinters v0.0.1
  [6d3278bc] ↑ ARCHModels v1.4.2 ⇒ v2.2.0
  [324d7699] - CategoricalArrays v0.9.7
  [a93c6f00] ↑ DataFrames v0.22.7 ⇒ v1.3.4
  [b429d917] + DensityInterface v0.4.0
  [31c24e10] ↑ Distributions v0.24.18 ⇒ v0.25.66
  [ffbed154] ↑ DocStringExtensions v0.8.6 ⇒ v0.9.1
  [e30172f5] ↑ Documenter v0.26.3 ⇒ v0.27.22
  [1a297f60] ↑ FillArrays v0.11.9 ⇒ v0.13.2
  [b5f81e59] ↑ IOCapture v0.1.1 ⇒ v0.2.2
  [e1d29d7a] ↑ Missings v0.4.5 ⇒ v1.0.2
  [46d2c3a1] + MuladdMacro v0.2.2
  [08abe8d2] ↑ PrettyTables v0.11.1 ⇒ v1.3.1
  [a2af1166] ↑ SortingAlgorithms v0.3.1 ⇒ v1.0.1
  [276daf66] ↑ SpecialFunctions v1.8.7 ⇒ v2.1.7
  [856f2bd8] - StructTypes v1.8.1
  [a6faba0b] ↑ ValueAtRisk v1.0.0 ⇒ v1.1.0
Precompiling project...
  1 dependency successfully precompiled in 12 seconds (78 already precompiled)
```

I see from running `registry update` above that a lot of packages are upgraded. Does that fix all your downgrades? (If not, it's probably because a dependency I have used requires older versions, but I'll look into it)

**Comment by shayandavoodii** [comment]
> The new version has been merged into the Julia Registry

Thanks! Great news.

> Does that fix all your downgrades?

Let's take a look:
```julia
  [49dc2e85] - Calculus v0.5.1
  [fa6b7ba4] - DualNumbers v0.6.8
  [34004b35] - HypergeometricFunctions v0.3.11
  [f2b01f46] ↓ Roots v2.0.2 ⇒ v1.2.0
  [4c63d2b9] ↓ StatsFuns v1.0.1 ⇒ v0.9.18
```
It's far better than before, as the number of conflicts decreased by 9.

**Comment by chm-von-tla** [comment]
Both `Roots` and `StatsFuns` are downgraded because the [ARCHModels](https://github.com/s-broda/ARCHModels.jl) package isn't compatible with the newer versions. 

That's all I can do in regards to this issue, so I'm gonna close it. If you have any issues/questions/etc. when using this package, after checking the documentation feel free to reach out!
